"""
Core configuration and constants for the UIDAI data processing pipeline.
Contains all API endpoints, reference data, and configuration settings.
"""

import os
from pathlib import Path
from typing import Dict, List, Any
import multiprocessing

# =============================================================================
# PATH CONFIGURATION
# =============================================================================

# Base paths
PROJECT_ROOT = Path(__file__).parent.parent.parent
DATASET_ROOT = PROJECT_ROOT / "Dataset"
ANALYSIS_ROOT = PROJECT_ROOT / "analysis"

# Input paths - CLEANED DATA (not dirty original data)
CORRECTED_DATASET_PATH = DATASET_ROOT / "corrected_dataset"
CLEANED_DATASET_PATH = DATASET_ROOT / "cleaned"

# Cleaned data file paths (USE THESE - 4.3M total records)
BIOMETRIC_CLEANED_PATH = CLEANED_DATASET_PATH / "biometric" / "biometric" / "final_cleaned_biometric.csv"
DEMOGRAPHIC_CLEANED_PATH = CLEANED_DATASET_PATH / "demographic" / "demographic" / "final_cleaned_demographic.csv"
ENROLLMENT_CLEANED_PATH = CLEANED_DATASET_PATH / "enrollment" / "enrollment" / "final_cleaned_enrollment.csv"

# Legacy paths (corrected but not fully cleaned)
BIOMETRIC_PATH = CORRECTED_DATASET_PATH / "biometric"
DEMOGRAPHIC_PATH = CORRECTED_DATASET_PATH / "demographic"
ENROLLMENT_PATH = CORRECTED_DATASET_PATH / "enrollement"

# Output paths
AUGMENTED_DATASET_PATH = DATASET_ROOT / "augmented"
RESULTS_PATH = ANALYSIS_ROOT / "results"
LOGS_PATH = PROJECT_ROOT / "logs"
DOCS_PATH = PROJECT_ROOT / "docs"

# Ensure output directories exist
for path in [CLEANED_DATASET_PATH, AUGMENTED_DATASET_PATH, RESULTS_PATH, LOGS_PATH, DOCS_PATH]:
    path.mkdir(parents=True, exist_ok=True)

# =============================================================================
# MULTIPROCESSING CONFIGURATION
# =============================================================================

# Use all available CPU cores
CPU_COUNT = multiprocessing.cpu_count()
CHUNK_SIZE = 10000  # Records per chunk for parallel processing

# =============================================================================
# API CONFIGURATION
# =============================================================================

# Open-Meteo APIs (Free, no API key required)
API_ENDPOINTS = {
    "weather_forecast": "https://api.open-meteo.com/v1/forecast",
    "historical_weather": "https://archive-api.open-meteo.com/v1/archive",
    "air_quality": "https://air-quality-api.open-meteo.com/v1/air-quality",
    "elevation": "https://api.open-meteo.com/v1/elevation",
    "geocoding": "https://geocoding-api.open-meteo.com/v1/search",
    "climate": "https://climate-api.open-meteo.com/v1/climate",
    
    # OpenStreetMap Nominatim (1 req/sec rate limit)
    "nominatim": "https://nominatim.openstreetmap.org/search",
    
    # India Post Pincode API
    "india_post": "https://api.postalpincode.in/pincode",
}

# API Rate Limits (requests per second)
API_RATE_LIMITS = {
    "weather_forecast": 100,  # Very generous
    "historical_weather": 10,
    "air_quality": 100,
    "elevation": 100,
    "geocoding": 10,
    "climate": 10,
    "nominatim": 1,  # Strict 1 req/sec
    "india_post": 5,
}

# Retry Configuration
RETRY_CONFIG = {
    "max_attempts": 5,
    "wait_min": 1,  # seconds
    "wait_max": 60,  # seconds
    "wait_multiplier": 2,
}

# =============================================================================
# INDIAN STATE REFERENCE DATA
# =============================================================================

# Standardized state names (all 36 states/UTs)
INDIA_STATES = {
    "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh",
    "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka",
    "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram",
    "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu",
    "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal",
    # Union Territories
    "Andaman And Nicobar Islands", "Chandigarh", "Dadra And Nagar Haveli And Daman And Diu",
    "Delhi", "Jammu And Kashmir", "Ladakh", "Lakshadweep", "Puducherry"
}

# State name variations mapping to standard names
STATE_NAME_MAPPING = {
    # Common variations
    "andhra pradesh": "Andhra Pradesh",
    "arunachal pradesh": "Arunachal Pradesh",
    "assam": "Assam",
    "bihar": "Bihar",
    "chhattisgarh": "Chhattisgarh",
    "chattisgarh": "Chhattisgarh",
    "chhatisgarh": "Chhattisgarh",  # Typo
    "goa": "Goa",
    "gujarat": "Gujarat",
    "haryana": "Haryana",
    "himachal pradesh": "Himachal Pradesh",
    "jharkhand": "Jharkhand",
    "karnataka": "Karnataka",
    "kerala": "Kerala",
    "madhya pradesh": "Madhya Pradesh",
    "maharashtra": "Maharashtra",
    "manipur": "Manipur",
    "meghalaya": "Meghalaya",
    "mizoram": "Mizoram",
    "nagaland": "Nagaland",
    "odisha": "Odisha",
    "orissa": "Odisha",  # Old name
    "punjab": "Punjab",
    "rajasthan": "Rajasthan",
    "sikkim": "Sikkim",
    "tamil nadu": "Tamil Nadu",
    "tamilnadu": "Tamil Nadu",
    "telangana": "Telangana",
    "tripura": "Tripura",
    "uttar pradesh": "Uttar Pradesh",
    "uttarakhand": "Uttarakhand",
    "uttaranchal": "Uttarakhand",  # Old name
    "west bengal": "West Bengal",
    "westbengal": "West Bengal",  # No space
    "west bangal": "West Bengal",  # Typo
    
    # Union Territories
    "andaman and nicobar islands": "Andaman And Nicobar Islands",
    "andaman & nicobar islands": "Andaman And Nicobar Islands",
    "andaman and nicobar": "Andaman And Nicobar Islands",
    "a & n islands": "Andaman And Nicobar Islands",
    "chandigarh": "Chandigarh",
    "dadra and nagar haveli and daman and diu": "Dadra And Nagar Haveli And Daman And Diu",
    "dadra & nagar haveli and daman & diu": "Dadra And Nagar Haveli And Daman And Diu",
    "dadra and nagar haveli": "Dadra And Nagar Haveli And Daman And Diu",
    "dadra & nagar haveli": "Dadra And Nagar Haveli And Daman And Diu",  # Common variation
    "daman and diu": "Dadra And Nagar Haveli And Daman And Diu",
    "daman & diu": "Dadra And Nagar Haveli And Daman And Diu",
    "d & n haveli": "Dadra And Nagar Haveli And Daman And Diu",
    "delhi": "Delhi",
    "nct of delhi": "Delhi",
    "new delhi": "Delhi",
    "jammu and kashmir": "Jammu And Kashmir",
    "jammu & kashmir": "Jammu And Kashmir",
    "j & k": "Jammu And Kashmir",
    "ladakh": "Ladakh",
    "lakshadweep": "Lakshadweep",
    "puducherry": "Puducherry",
    "pondicherry": "Puducherry",
}

# =============================================================================
# REGION MAPPING (Geographic Regions of India)
# =============================================================================

REGION_MAPPING = {
    # North India
    "Delhi": "North",
    "Haryana": "North",
    "Himachal Pradesh": "North",
    "Jammu And Kashmir": "North",
    "Ladakh": "North",
    "Punjab": "North",
    "Rajasthan": "North",
    "Uttarakhand": "North",
    "Chandigarh": "North",
    
    # South India
    "Andhra Pradesh": "South",
    "Karnataka": "South",
    "Kerala": "South",
    "Tamil Nadu": "South",
    "Telangana": "South",
    "Puducherry": "South",
    "Lakshadweep": "South",
    
    # East India
    "Bihar": "East",
    "Jharkhand": "East",
    "Odisha": "East",
    "West Bengal": "East",
    "Sikkim": "East",
    
    # West India
    "Goa": "West",
    "Gujarat": "West",
    "Maharashtra": "West",
    "Dadra And Nagar Haveli And Daman And Diu": "West",
    
    # Central India
    "Chhattisgarh": "Central",
    "Madhya Pradesh": "Central",
    "Uttar Pradesh": "Central",
    
    # Northeast India
    "Arunachal Pradesh": "Northeast",
    "Assam": "Northeast",
    "Manipur": "Northeast",
    "Meghalaya": "Northeast",
    "Mizoram": "Northeast",
    "Nagaland": "Northeast",
    "Tripura": "Northeast",
    
    # Islands
    "Andaman And Nicobar Islands": "Islands",
}

# =============================================================================
# STATE CENSUS DATA (Census 2011 + Updates)
# =============================================================================

INDIA_CENSUS_DATA: Dict[str, Dict[str, Any]] = {
    "Andhra Pradesh": {
        "population_2011": 49386799,
        "area_sq_km": 162968,
        "density_per_sq_km": 303,
        "literacy_rate": 67.02,
        "sex_ratio": 993,
        "capital": "Amaravati",
        "region": "South India",
        "zone": "Southern",
        "rainfall_zone": "Medium",
        "earthquake_zone": "II",
        "climate_type": "Tropical",
        "avg_temp_min_c": 20,
        "avg_temp_max_c": 38,
        "avg_rainfall_mm": 900,
        "per_capita_income_inr": 170000,
        "hdi": 0.65,
        "major_language": "Telugu",
        "time_zone": "IST",
        "coastal": True,
    },
    "Arunachal Pradesh": {
        "population_2011": 1383727,
        "area_sq_km": 83743,
        "density_per_sq_km": 17,
        "literacy_rate": 65.38,
        "sex_ratio": 938,
        "capital": "Itanagar",
        "region": "Northeast India",
        "zone": "Northeastern",
        "rainfall_zone": "High",
        "earthquake_zone": "V",
        "climate_type": "Alpine/Subtropical",
        "avg_temp_min_c": 5,
        "avg_temp_max_c": 25,
        "avg_rainfall_mm": 3000,
        "per_capita_income_inr": 110000,
        "hdi": 0.55,
        "major_language": "Nyishi",
        "time_zone": "IST",
        "coastal": False,
    },
    "Assam": {
        "population_2011": 31205576,
        "area_sq_km": 78438,
        "density_per_sq_km": 398,
        "literacy_rate": 72.19,
        "sex_ratio": 958,
        "capital": "Dispur",
        "region": "Northeast India",
        "zone": "Northeastern",
        "rainfall_zone": "Very High",
        "earthquake_zone": "V",
        "climate_type": "Subtropical",
        "avg_temp_min_c": 12,
        "avg_temp_max_c": 35,
        "avg_rainfall_mm": 2800,
        "per_capita_income_inr": 95000,
        "hdi": 0.57,
        "major_language": "Assamese",
        "time_zone": "IST",
        "coastal": False,
    },
    "Bihar": {
        "population_2011": 104099452,
        "area_sq_km": 94163,
        "density_per_sq_km": 1106,
        "literacy_rate": 61.80,
        "sex_ratio": 918,
        "capital": "Patna",
        "region": "East India",
        "zone": "Eastern",
        "rainfall_zone": "Medium",
        "earthquake_zone": "IV",
        "climate_type": "Humid Subtropical",
        "avg_temp_min_c": 10,
        "avg_temp_max_c": 42,
        "avg_rainfall_mm": 1200,
        "per_capita_income_inr": 50000,
        "hdi": 0.51,
        "major_language": "Hindi",
        "time_zone": "IST",
        "coastal": False,
    },
    "Chhattisgarh": {
        "population_2011": 25545198,
        "area_sq_km": 135191,
        "density_per_sq_km": 189,
        "literacy_rate": 70.28,
        "sex_ratio": 991,
        "capital": "Raipur",
        "region": "Central India",
        "zone": "Central",
        "rainfall_zone": "Medium",
        "earthquake_zone": "II",
        "climate_type": "Tropical",
        "avg_temp_min_c": 15,
        "avg_temp_max_c": 42,
        "avg_rainfall_mm": 1400,
        "per_capita_income_inr": 100000,
        "hdi": 0.54,
        "major_language": "Hindi/Chhattisgarhi",
        "time_zone": "IST",
        "coastal": False,
    },
    "Goa": {
        "population_2011": 1458545,
        "area_sq_km": 3702,
        "density_per_sq_km": 394,
        "literacy_rate": 88.70,
        "sex_ratio": 973,
        "capital": "Panaji",
        "region": "West India",
        "zone": "Western",
        "rainfall_zone": "High",
        "earthquake_zone": "III",
        "climate_type": "Tropical Monsoon",
        "avg_temp_min_c": 20,
        "avg_temp_max_c": 33,
        "avg_rainfall_mm": 3000,
        "per_capita_income_inr": 450000,
        "hdi": 0.76,
        "major_language": "Konkani",
        "time_zone": "IST",
        "coastal": True,
    },
    "Gujarat": {
        "population_2011": 60439692,
        "area_sq_km": 196024,
        "density_per_sq_km": 308,
        "literacy_rate": 78.03,
        "sex_ratio": 919,
        "capital": "Gandhinagar",
        "region": "West India",
        "zone": "Western",
        "rainfall_zone": "Low",
        "earthquake_zone": "III-V",
        "climate_type": "Semi-arid/Arid",
        "avg_temp_min_c": 15,
        "avg_temp_max_c": 42,
        "avg_rainfall_mm": 800,
        "per_capita_income_inr": 200000,
        "hdi": 0.67,
        "major_language": "Gujarati",
        "time_zone": "IST",
        "coastal": True,
    },
    "Haryana": {
        "population_2011": 25351462,
        "area_sq_km": 44212,
        "density_per_sq_km": 573,
        "literacy_rate": 75.55,
        "sex_ratio": 879,
        "capital": "Chandigarh",
        "region": "North India",
        "zone": "Northern",
        "rainfall_zone": "Low",
        "earthquake_zone": "IV",
        "climate_type": "Semi-arid",
        "avg_temp_min_c": 5,
        "avg_temp_max_c": 45,
        "avg_rainfall_mm": 600,
        "per_capita_income_inr": 225000,
        "hdi": 0.71,
        "major_language": "Hindi/Haryanvi",
        "time_zone": "IST",
        "coastal": False,
    },
    "Himachal Pradesh": {
        "population_2011": 6864602,
        "area_sq_km": 55673,
        "density_per_sq_km": 123,
        "literacy_rate": 82.80,
        "sex_ratio": 972,
        "capital": "Shimla",
        "region": "North India",
        "zone": "Northern",
        "rainfall_zone": "Medium",
        "earthquake_zone": "IV-V",
        "climate_type": "Alpine/Subtropical",
        "avg_temp_min_c": -5,
        "avg_temp_max_c": 30,
        "avg_rainfall_mm": 1500,
        "per_capita_income_inr": 175000,
        "hdi": 0.72,
        "major_language": "Hindi",
        "time_zone": "IST",
        "coastal": False,
    },
    "Jharkhand": {
        "population_2011": 32988134,
        "area_sq_km": 79714,
        "density_per_sq_km": 414,
        "literacy_rate": 66.41,
        "sex_ratio": 948,
        "capital": "Ranchi",
        "region": "East India",
        "zone": "Eastern",
        "rainfall_zone": "Medium",
        "earthquake_zone": "II-III",
        "climate_type": "Tropical",
        "avg_temp_min_c": 10,
        "avg_temp_max_c": 42,
        "avg_rainfall_mm": 1300,
        "per_capita_income_inr": 75000,
        "hdi": 0.51,
        "major_language": "Hindi",
        "time_zone": "IST",
        "coastal": False,
    },
    "Karnataka": {
        "population_2011": 61095297,
        "area_sq_km": 191791,
        "density_per_sq_km": 319,
        "literacy_rate": 75.36,
        "sex_ratio": 973,
        "capital": "Bengaluru",
        "region": "South India",
        "zone": "Southern",
        "rainfall_zone": "Medium",
        "earthquake_zone": "II-III",
        "climate_type": "Tropical",
        "avg_temp_min_c": 18,
        "avg_temp_max_c": 35,
        "avg_rainfall_mm": 1200,
        "per_capita_income_inr": 220000,
        "hdi": 0.68,
        "major_language": "Kannada",
        "time_zone": "IST",
        "coastal": True,
    },
    "Kerala": {
        "population_2011": 33406061,
        "area_sq_km": 38863,
        "density_per_sq_km": 860,
        "literacy_rate": 93.91,
        "sex_ratio": 1084,
        "capital": "Thiruvananthapuram",
        "region": "South India",
        "zone": "Southern",
        "rainfall_zone": "Very High",
        "earthquake_zone": "III",
        "climate_type": "Tropical Monsoon",
        "avg_temp_min_c": 22,
        "avg_temp_max_c": 34,
        "avg_rainfall_mm": 3000,
        "per_capita_income_inr": 195000,
        "hdi": 0.78,
        "major_language": "Malayalam",
        "time_zone": "IST",
        "coastal": True,
    },
    "Madhya Pradesh": {
        "population_2011": 72626809,
        "area_sq_km": 308245,
        "density_per_sq_km": 236,
        "literacy_rate": 69.32,
        "sex_ratio": 931,
        "capital": "Bhopal",
        "region": "Central India",
        "zone": "Central",
        "rainfall_zone": "Medium",
        "earthquake_zone": "II-III",
        "climate_type": "Subtropical",
        "avg_temp_min_c": 10,
        "avg_temp_max_c": 44,
        "avg_rainfall_mm": 1100,
        "per_capita_income_inr": 95000,
        "hdi": 0.55,
        "major_language": "Hindi",
        "time_zone": "IST",
        "coastal": False,
    },
    "Maharashtra": {
        "population_2011": 112374333,
        "area_sq_km": 307713,
        "density_per_sq_km": 365,
        "literacy_rate": 82.34,
        "sex_ratio": 929,
        "capital": "Mumbai",
        "region": "West India",
        "zone": "Western",
        "rainfall_zone": "Medium",
        "earthquake_zone": "III",
        "climate_type": "Tropical",
        "avg_temp_min_c": 15,
        "avg_temp_max_c": 40,
        "avg_rainfall_mm": 1500,
        "per_capita_income_inr": 210000,
        "hdi": 0.70,
        "major_language": "Marathi",
        "time_zone": "IST",
        "coastal": True,
    },
    "Manipur": {
        "population_2011": 2855794,
        "area_sq_km": 22327,
        "density_per_sq_km": 128,
        "literacy_rate": 79.85,
        "sex_ratio": 985,
        "capital": "Imphal",
        "region": "Northeast India",
        "zone": "Northeastern",
        "rainfall_zone": "High",
        "earthquake_zone": "V",
        "climate_type": "Subtropical",
        "avg_temp_min_c": 5,
        "avg_temp_max_c": 30,
        "avg_rainfall_mm": 1500,
        "per_capita_income_inr": 70000,
        "hdi": 0.56,
        "major_language": "Meitei",
        "time_zone": "IST",
        "coastal": False,
    },
    "Meghalaya": {
        "population_2011": 2966889,
        "area_sq_km": 22429,
        "density_per_sq_km": 132,
        "literacy_rate": 74.43,
        "sex_ratio": 989,
        "capital": "Shillong",
        "region": "Northeast India",
        "zone": "Northeastern",
        "rainfall_zone": "Very High",
        "earthquake_zone": "V",
        "climate_type": "Subtropical Highland",
        "avg_temp_min_c": 5,
        "avg_temp_max_c": 25,
        "avg_rainfall_mm": 4000,
        "per_capita_income_inr": 85000,
        "hdi": 0.58,
        "major_language": "Khasi/Garo",
        "time_zone": "IST",
        "coastal": False,
    },
    "Mizoram": {
        "population_2011": 1097206,
        "area_sq_km": 21081,
        "density_per_sq_km": 52,
        "literacy_rate": 91.33,
        "sex_ratio": 976,
        "capital": "Aizawl",
        "region": "Northeast India",
        "zone": "Northeastern",
        "rainfall_zone": "High",
        "earthquake_zone": "V",
        "climate_type": "Subtropical",
        "avg_temp_min_c": 10,
        "avg_temp_max_c": 28,
        "avg_rainfall_mm": 2500,
        "per_capita_income_inr": 115000,
        "hdi": 0.65,
        "major_language": "Mizo",
        "time_zone": "IST",
        "coastal": False,
    },
    "Nagaland": {
        "population_2011": 1978502,
        "area_sq_km": 16579,
        "density_per_sq_km": 119,
        "literacy_rate": 79.55,
        "sex_ratio": 931,
        "capital": "Kohima",
        "region": "Northeast India",
        "zone": "Northeastern",
        "rainfall_zone": "High",
        "earthquake_zone": "V",
        "climate_type": "Subtropical",
        "avg_temp_min_c": 5,
        "avg_temp_max_c": 28,
        "avg_rainfall_mm": 2000,
        "per_capita_income_inr": 95000,
        "hdi": 0.60,
        "major_language": "English/Naga languages",
        "time_zone": "IST",
        "coastal": False,
    },
    "Odisha": {
        "population_2011": 41974218,
        "area_sq_km": 155707,
        "density_per_sq_km": 270,
        "literacy_rate": 72.87,
        "sex_ratio": 979,
        "capital": "Bhubaneswar",
        "region": "East India",
        "zone": "Eastern",
        "rainfall_zone": "High",
        "earthquake_zone": "II-III",
        "climate_type": "Tropical",
        "avg_temp_min_c": 15,
        "avg_temp_max_c": 40,
        "avg_rainfall_mm": 1500,
        "per_capita_income_inr": 100000,
        "hdi": 0.57,
        "major_language": "Odia",
        "time_zone": "IST",
        "coastal": True,
    },
    "Punjab": {
        "population_2011": 27743338,
        "area_sq_km": 50362,
        "density_per_sq_km": 551,
        "literacy_rate": 75.84,
        "sex_ratio": 895,
        "capital": "Chandigarh",
        "region": "North India",
        "zone": "Northern",
        "rainfall_zone": "Low",
        "earthquake_zone": "IV",
        "climate_type": "Semi-arid",
        "avg_temp_min_c": 5,
        "avg_temp_max_c": 44,
        "avg_rainfall_mm": 650,
        "per_capita_income_inr": 145000,
        "hdi": 0.69,
        "major_language": "Punjabi",
        "time_zone": "IST",
        "coastal": False,
    },
    "Rajasthan": {
        "population_2011": 68548437,
        "area_sq_km": 342239,
        "density_per_sq_km": 200,
        "literacy_rate": 66.11,
        "sex_ratio": 928,
        "capital": "Jaipur",
        "region": "North India",
        "zone": "Northern",
        "rainfall_zone": "Very Low",
        "earthquake_zone": "II-III",
        "climate_type": "Arid/Semi-arid",
        "avg_temp_min_c": 8,
        "avg_temp_max_c": 48,
        "avg_rainfall_mm": 500,
        "per_capita_income_inr": 115000,
        "hdi": 0.60,
        "major_language": "Hindi/Rajasthani",
        "time_zone": "IST",
        "coastal": False,
    },
    "Sikkim": {
        "population_2011": 610577,
        "area_sq_km": 7096,
        "density_per_sq_km": 86,
        "literacy_rate": 81.42,
        "sex_ratio": 890,
        "capital": "Gangtok",
        "region": "Northeast India",
        "zone": "Northeastern",
        "rainfall_zone": "High",
        "earthquake_zone": "IV",
        "climate_type": "Alpine/Subtropical",
        "avg_temp_min_c": -5,
        "avg_temp_max_c": 22,
        "avg_rainfall_mm": 3000,
        "per_capita_income_inr": 260000,
        "hdi": 0.72,
        "major_language": "Nepali",
        "time_zone": "IST",
        "coastal": False,
    },
    "Tamil Nadu": {
        "population_2011": 72147030,
        "area_sq_km": 130058,
        "density_per_sq_km": 555,
        "literacy_rate": 80.09,
        "sex_ratio": 996,
        "capital": "Chennai",
        "region": "South India",
        "zone": "Southern",
        "rainfall_zone": "Medium",
        "earthquake_zone": "II-III",
        "climate_type": "Tropical",
        "avg_temp_min_c": 20,
        "avg_temp_max_c": 38,
        "avg_rainfall_mm": 950,
        "per_capita_income_inr": 195000,
        "hdi": 0.71,
        "major_language": "Tamil",
        "time_zone": "IST",
        "coastal": True,
    },
    "Telangana": {
        "population_2011": 35003674,
        "area_sq_km": 112077,
        "density_per_sq_km": 312,
        "literacy_rate": 66.54,
        "sex_ratio": 988,
        "capital": "Hyderabad",
        "region": "South India",
        "zone": "Southern",
        "rainfall_zone": "Medium",
        "earthquake_zone": "II",
        "climate_type": "Tropical",
        "avg_temp_min_c": 18,
        "avg_temp_max_c": 42,
        "avg_rainfall_mm": 900,
        "per_capita_income_inr": 235000,
        "hdi": 0.67,
        "major_language": "Telugu",
        "time_zone": "IST",
        "coastal": False,
    },
    "Tripura": {
        "population_2011": 3673917,
        "area_sq_km": 10486,
        "density_per_sq_km": 350,
        "literacy_rate": 87.22,
        "sex_ratio": 960,
        "capital": "Agartala",
        "region": "Northeast India",
        "zone": "Northeastern",
        "rainfall_zone": "High",
        "earthquake_zone": "V",
        "climate_type": "Tropical Monsoon",
        "avg_temp_min_c": 12,
        "avg_temp_max_c": 35,
        "avg_rainfall_mm": 2200,
        "per_capita_income_inr": 110000,
        "hdi": 0.62,
        "major_language": "Bengali/Kokborok",
        "time_zone": "IST",
        "coastal": False,
    },
    "Uttar Pradesh": {
        "population_2011": 199812341,
        "area_sq_km": 240928,
        "density_per_sq_km": 829,
        "literacy_rate": 67.68,
        "sex_ratio": 912,
        "capital": "Lucknow",
        "region": "North India",
        "zone": "Northern",
        "rainfall_zone": "Medium",
        "earthquake_zone": "II-IV",
        "climate_type": "Humid Subtropical",
        "avg_temp_min_c": 5,
        "avg_temp_max_c": 45,
        "avg_rainfall_mm": 1000,
        "per_capita_income_inr": 65000,
        "hdi": 0.54,
        "major_language": "Hindi",
        "time_zone": "IST",
        "coastal": False,
    },
    "Uttarakhand": {
        "population_2011": 10086292,
        "area_sq_km": 53483,
        "density_per_sq_km": 189,
        "literacy_rate": 78.82,
        "sex_ratio": 963,
        "capital": "Dehradun",
        "region": "North India",
        "zone": "Northern",
        "rainfall_zone": "Medium",
        "earthquake_zone": "IV-V",
        "climate_type": "Alpine/Subtropical",
        "avg_temp_min_c": -5,
        "avg_temp_max_c": 35,
        "avg_rainfall_mm": 1600,
        "per_capita_income_inr": 165000,
        "hdi": 0.68,
        "major_language": "Hindi/Garhwali/Kumaoni",
        "time_zone": "IST",
        "coastal": False,
    },
    "West Bengal": {
        "population_2011": 91276115,
        "area_sq_km": 88752,
        "density_per_sq_km": 1028,
        "literacy_rate": 76.26,
        "sex_ratio": 950,
        "capital": "Kolkata",
        "region": "East India",
        "zone": "Eastern",
        "rainfall_zone": "High",
        "earthquake_zone": "III-IV",
        "climate_type": "Tropical",
        "avg_temp_min_c": 12,
        "avg_temp_max_c": 38,
        "avg_rainfall_mm": 1750,
        "per_capita_income_inr": 110000,
        "hdi": 0.64,
        "major_language": "Bengali",
        "time_zone": "IST",
        "coastal": True,
    },
    # Union Territories
    "Andaman And Nicobar Islands": {
        "population_2011": 380581,
        "area_sq_km": 8249,
        "density_per_sq_km": 46,
        "literacy_rate": 86.63,
        "sex_ratio": 876,
        "capital": "Port Blair",
        "region": "Island",
        "zone": "Islands",
        "rainfall_zone": "Very High",
        "earthquake_zone": "V",
        "climate_type": "Tropical Maritime",
        "avg_temp_min_c": 22,
        "avg_temp_max_c": 31,
        "avg_rainfall_mm": 3000,
        "per_capita_income_inr": 130000,
        "hdi": 0.68,
        "major_language": "Hindi/Bengali",
        "time_zone": "IST",
        "coastal": True,
    },
    "Chandigarh": {
        "population_2011": 1055450,
        "area_sq_km": 114,
        "density_per_sq_km": 9258,
        "literacy_rate": 86.05,
        "sex_ratio": 818,
        "capital": "Chandigarh",
        "region": "North India",
        "zone": "Northern",
        "rainfall_zone": "Low",
        "earthquake_zone": "IV",
        "climate_type": "Humid Subtropical",
        "avg_temp_min_c": 5,
        "avg_temp_max_c": 40,
        "avg_rainfall_mm": 1100,
        "per_capita_income_inr": 210000,
        "hdi": 0.77,
        "major_language": "Hindi/Punjabi",
        "time_zone": "IST",
        "coastal": False,
    },
    "Dadra And Nagar Haveli And Daman And Diu": {
        "population_2011": 586956,
        "area_sq_km": 603,
        "density_per_sq_km": 973,
        "literacy_rate": 77.65,
        "sex_ratio": 774,
        "capital": "Daman",
        "region": "West India",
        "zone": "Western",
        "rainfall_zone": "High",
        "earthquake_zone": "III",
        "climate_type": "Tropical",
        "avg_temp_min_c": 18,
        "avg_temp_max_c": 36,
        "avg_rainfall_mm": 2500,
        "per_capita_income_inr": 350000,
        "hdi": 0.65,
        "major_language": "Gujarati",
        "time_zone": "IST",
        "coastal": True,
    },
    "Delhi": {
        "population_2011": 16787941,
        "area_sq_km": 1484,
        "density_per_sq_km": 11320,
        "literacy_rate": 86.21,
        "sex_ratio": 868,
        "capital": "New Delhi",
        "region": "North India",
        "zone": "Northern",
        "rainfall_zone": "Low",
        "earthquake_zone": "IV",
        "climate_type": "Semi-arid",
        "avg_temp_min_c": 5,
        "avg_temp_max_c": 45,
        "avg_rainfall_mm": 800,
        "per_capita_income_inr": 360000,
        "hdi": 0.75,
        "major_language": "Hindi",
        "time_zone": "IST",
        "coastal": False,
    },
    "Jammu And Kashmir": {
        "population_2011": 12541302,
        "area_sq_km": 42241,
        "density_per_sq_km": 297,
        "literacy_rate": 67.16,
        "sex_ratio": 889,
        "capital": "Srinagar/Jammu",
        "region": "North India",
        "zone": "Northern",
        "rainfall_zone": "Medium",
        "earthquake_zone": "IV-V",
        "climate_type": "Alpine/Subtropical",
        "avg_temp_min_c": -10,
        "avg_temp_max_c": 35,
        "avg_rainfall_mm": 1200,
        "per_capita_income_inr": 90000,
        "hdi": 0.65,
        "major_language": "Urdu/Kashmiri/Dogri",
        "time_zone": "IST",
        "coastal": False,
    },
    "Ladakh": {
        "population_2011": 274289,
        "area_sq_km": 59146,
        "density_per_sq_km": 5,
        "literacy_rate": 77.20,
        "sex_ratio": 690,
        "capital": "Leh",
        "region": "North India",
        "zone": "Northern",
        "rainfall_zone": "Very Low",
        "earthquake_zone": "IV-V",
        "climate_type": "Cold Desert",
        "avg_temp_min_c": -25,
        "avg_temp_max_c": 25,
        "avg_rainfall_mm": 100,
        "per_capita_income_inr": 85000,
        "hdi": 0.62,
        "major_language": "Ladakhi/Tibetan",
        "time_zone": "IST",
        "coastal": False,
    },
    "Lakshadweep": {
        "population_2011": 64473,
        "area_sq_km": 32,
        "density_per_sq_km": 2015,
        "literacy_rate": 91.85,
        "sex_ratio": 946,
        "capital": "Kavaratti",
        "region": "Island",
        "zone": "Islands",
        "rainfall_zone": "High",
        "earthquake_zone": "I",
        "climate_type": "Tropical Maritime",
        "avg_temp_min_c": 25,
        "avg_temp_max_c": 32,
        "avg_rainfall_mm": 1600,
        "per_capita_income_inr": 75000,
        "hdi": 0.75,
        "major_language": "Malayalam",
        "time_zone": "IST",
        "coastal": True,
    },
    "Puducherry": {
        "population_2011": 1247953,
        "area_sq_km": 479,
        "density_per_sq_km": 2605,
        "literacy_rate": 85.85,
        "sex_ratio": 1037,
        "capital": "Puducherry",
        "region": "South India",
        "zone": "Southern",
        "rainfall_zone": "Medium",
        "earthquake_zone": "II-III",
        "climate_type": "Tropical",
        "avg_temp_min_c": 22,
        "avg_temp_max_c": 36,
        "avg_rainfall_mm": 1300,
        "per_capita_income_inr": 170000,
        "hdi": 0.73,
        "major_language": "Tamil/French",
        "time_zone": "IST",
        "coastal": True,
    },
}

# =============================================================================
# PINCODE REGION MAPPING
# =============================================================================

# First two digits of pincode map to regions
PINCODE_REGION_MAP = {
    # Delhi (11)
    "11": {"region": "Delhi NCR", "state": "Delhi"},
    # Haryana (12-13)
    "12": {"region": "Haryana", "state": "Haryana"},
    "13": {"region": "Haryana/Punjab", "state": "Haryana"},
    # Punjab (14-16)
    "14": {"region": "Punjab", "state": "Punjab"},
    "15": {"region": "Punjab", "state": "Punjab"},
    "16": {"region": "Punjab/HP", "state": "Punjab"},
    # Himachal Pradesh (17)
    "17": {"region": "Himachal Pradesh", "state": "Himachal Pradesh"},
    # Chandigarh (16)
    # Jammu & Kashmir (18-19)
    "18": {"region": "Jammu", "state": "Jammu And Kashmir"},
    "19": {"region": "Kashmir", "state": "Jammu And Kashmir"},
    # Uttar Pradesh (20-28)
    "20": {"region": "Western UP", "state": "Uttar Pradesh"},
    "21": {"region": "Western UP", "state": "Uttar Pradesh"},
    "22": {"region": "Central UP", "state": "Uttar Pradesh"},
    "23": {"region": "Central UP", "state": "Uttar Pradesh"},
    "24": {"region": "Eastern UP", "state": "Uttar Pradesh"},
    "25": {"region": "Eastern UP", "state": "Uttar Pradesh"},
    "26": {"region": "Northern UP", "state": "Uttar Pradesh"},
    "27": {"region": "Eastern UP", "state": "Uttar Pradesh"},
    "28": {"region": "Eastern UP", "state": "Uttar Pradesh"},
    # Rajasthan (30-34)
    "30": {"region": "Rajasthan", "state": "Rajasthan"},
    "31": {"region": "Rajasthan", "state": "Rajasthan"},
    "32": {"region": "Rajasthan", "state": "Rajasthan"},
    "33": {"region": "Rajasthan", "state": "Rajasthan"},
    "34": {"region": "Rajasthan", "state": "Rajasthan"},
    # Gujarat (36-39)
    "36": {"region": "Gujarat", "state": "Gujarat"},
    "37": {"region": "Gujarat", "state": "Gujarat"},
    "38": {"region": "Gujarat", "state": "Gujarat"},
    "39": {"region": "Gujarat", "state": "Gujarat"},
    # Maharashtra (40-44)
    "40": {"region": "Maharashtra", "state": "Maharashtra"},
    "41": {"region": "Maharashtra", "state": "Maharashtra"},
    "42": {"region": "Maharashtra", "state": "Maharashtra"},
    "43": {"region": "Maharashtra", "state": "Maharashtra"},
    "44": {"region": "Maharashtra", "state": "Maharashtra"},
    # Madhya Pradesh (45-49)
    "45": {"region": "Madhya Pradesh", "state": "Madhya Pradesh"},
    "46": {"region": "Madhya Pradesh", "state": "Madhya Pradesh"},
    "47": {"region": "Madhya Pradesh", "state": "Madhya Pradesh"},
    "48": {"region": "Madhya Pradesh", "state": "Madhya Pradesh"},
    "49": {"region": "Chhattisgarh", "state": "Chhattisgarh"},
    # Andhra Pradesh/Telangana (50-53)
    "50": {"region": "Telangana", "state": "Telangana"},
    "51": {"region": "Andhra Pradesh/Telangana", "state": "Telangana"},
    "52": {"region": "Andhra Pradesh", "state": "Andhra Pradesh"},
    "53": {"region": "Andhra Pradesh", "state": "Andhra Pradesh"},
    # Karnataka (56-59)
    "56": {"region": "Karnataka", "state": "Karnataka"},
    "57": {"region": "Karnataka", "state": "Karnataka"},
    "58": {"region": "Karnataka", "state": "Karnataka"},
    "59": {"region": "Karnataka", "state": "Karnataka"},
    # Tamil Nadu (60-64)
    "60": {"region": "Tamil Nadu", "state": "Tamil Nadu"},
    "61": {"region": "Tamil Nadu", "state": "Tamil Nadu"},
    "62": {"region": "Tamil Nadu", "state": "Tamil Nadu"},
    "63": {"region": "Tamil Nadu", "state": "Tamil Nadu"},
    "64": {"region": "Tamil Nadu", "state": "Tamil Nadu"},
    # Kerala (67-69)
    "67": {"region": "Kerala", "state": "Kerala"},
    "68": {"region": "Kerala", "state": "Kerala"},
    "69": {"region": "Kerala", "state": "Kerala"},
    # West Bengal (70-74)
    "70": {"region": "West Bengal", "state": "West Bengal"},
    "71": {"region": "West Bengal", "state": "West Bengal"},
    "72": {"region": "West Bengal", "state": "West Bengal"},
    "73": {"region": "West Bengal", "state": "West Bengal"},
    "74": {"region": "West Bengal", "state": "West Bengal"},
    # Odisha (75-77)
    "75": {"region": "Odisha", "state": "Odisha"},
    "76": {"region": "Odisha", "state": "Odisha"},
    "77": {"region": "Odisha", "state": "Odisha"},
    # Assam & Northeast (78-79)
    "78": {"region": "Assam", "state": "Assam"},
    "79": {"region": "Northeast", "state": "Assam"},
    # Bihar/Jharkhand (80-85)
    "80": {"region": "Bihar", "state": "Bihar"},
    "81": {"region": "Bihar", "state": "Bihar"},
    "82": {"region": "Bihar/Jharkhand", "state": "Bihar"},
    "83": {"region": "Jharkhand", "state": "Jharkhand"},
    "84": {"region": "Bihar", "state": "Bihar"},
    "85": {"region": "Jharkhand", "state": "Jharkhand"},
    # Goa (40)
    # Arunachal Pradesh (79)
    # Sikkim (73)
}

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================

LOG_FORMAT = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
LOG_DATE_FORMAT = "%Y-%m-%d %H:%M:%S"
LOG_LEVEL = "INFO"

# =============================================================================
# CSV VALIDATION CONFIGURATION
# =============================================================================

# Expected columns for each dataset type
EXPECTED_COLUMNS = {
    "biometric": ["date", "state", "district", "pincode", "bio_age_5_17", "bio_age_17_", "district_external_source"],
    "demographic": ["date", "state", "district", "pincode", "demo_age_5_17", "demo_age_17_"],
    "enrollment": ["date", "state", "district", "pincode", "age_0_5", "age_5_17", "age_18_greater"],
}

# Invalid characters to check in CSV fields
INVALID_CHARS = ['\x00', '\r\n', '\n\r']

# Fields that should not be null
NON_NULL_FIELDS = ["date", "state", "district", "pincode"]
